export const Privacy = () => {
    return (
        <section>
            <h2>Политика конфиденциальности</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos ratione aut distinctio, error sint dignissimos voluptatum itaque voluptatem minima, veritatis animi atque quae quibusdam omnis assumenda iure fugit, sequi enim.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos ratione aut distinctio, error sint dignissimos voluptatum itaque voluptatem minima, veritatis animi atque quae quibusdam omnis assumenda iure fugit, sequi enim.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos ratione aut distinctio, error sint dignissimos voluptatum itaque voluptatem minima, veritatis animi atque quae quibusdam omnis assumenda iure fugit, sequi enim.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos ratione aut distinctio, error sint dignissimos voluptatum itaque voluptatem minima, veritatis animi atque quae quibusdam omnis assumenda iure fugit, sequi enim.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos ratione aut distinctio, error sint dignissimos voluptatum itaque voluptatem minima, veritatis animi atque quae quibusdam omnis assumenda iure fugit, sequi enim.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos ratione aut distinctio, error sint dignissimos voluptatum itaque voluptatem minima, veritatis animi atque quae quibusdam omnis assumenda iure fugit, sequi enim.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos ratione aut distinctio, error sint dignissimos voluptatum itaque voluptatem minima, veritatis animi atque quae quibusdam omnis assumenda iure fugit, sequi enim.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos ratione aut distinctio, error sint dignissimos voluptatum itaque voluptatem minima, veritatis animi atque quae quibusdam omnis assumenda iure fugit, sequi enim.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos ratione aut distinctio, error sint dignissimos voluptatum itaque voluptatem minima, veritatis animi atque quae quibusdam omnis assumenda iure fugit, sequi enim.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos ratione aut distinctio, error sint dignissimos voluptatum itaque voluptatem minima, veritatis animi atque quae quibusdam omnis assumenda iure fugit, sequi enim.
            </p>
        </section>
    )
}